// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  /// Temporarily bypassing platform verification.
  /// Change `android` to `windows` if testing on Windows.
  static FirebaseOptions get currentPlatform => android;  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFPgt5PvhHI1U9OB0QGYatfWSF7yCDoI',
    appId: '1:747765863477:android:2c0fe2ef813cfc14f88d7c',
    messagingSenderId: '747765863477',
    projectId: 'finderbase-123',
    storageBucket: 'finderbase-123.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4K7G_4_ieG5lBomqCQnT_j1bxHnxRr1M',
    appId: '1:747765863477:web:218f20dc34b1d0c9f88d7c',
    messagingSenderId: '747765863477',
    projectId: 'finderbase-123',
    authDomain: 'finderbase-123.firebaseapp.com',
    storageBucket: 'finderbase-123.appspot.com',
  );
}
